name: Auto Minify All Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Minify all files
        uses: squeakycheese75/minify-all@v1
        with:
          exclude: 'node_modules'
          extensions: 'html,css,js,json'

      - name: Commit changes
        run: |
          git config --global user.name "Sainath Arjun"
          git config --global user.email "sainatharjun4@gmail.com"
          git add .
          git commit -m "Minify all files"
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
