name: Auto Minify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  auto-minify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Auto Minify
      uses: actions/upload-artifact@v2
      with:
        name: minified-files
        path: |
          **/*.html
          **/*.css
          **/*.js
